version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    command: yarn run sls offline --host 0.0.0.0
    ports: ['8080:8080']
    volumes:
      - .:/var/task
      - aws:/root/.aws
      - ./layers/canvas/lib:/opt/lib
      - node_modules:/var/task/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v6
    depends_on:
      - dynamodb

  dynamodb:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    command: yarn run sls dynamodb start
    ports: ['8000:8000']
    volumes:
      - .:/var/task
      - node_modules:/var/task/node_modules

  infra:
    build:
      context: .
      dockerfile: ./containers/infra/Dockerfile
    volumes:
      - .:/app
      - aws:/root/.aws
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

volumes:
  aws:
  node_modules:
  yarn_cache:
