service:
  name: "${self:custom.product}"

frameworkVersion: "2"

custom:
  product: "lgtm-generator-api"
  prefix: "${self:custom.product}-${self:provider.stage}"
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
  serverless-offline:
    httpPort: 8080
    useChildProcesses: true

plugins:
  - "serverless-webpack"
  - "serverless-offline"

provider:
  name: "aws"
  profile: "default"
  region: "us-east-1"
  runtime: "nodejs12.x"
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

layers:
  canvas:
    name: "${self:custom.prefix}-canvas"
    path: "layers/canvas"

functions:
  createLgtm:
    timeout: 30
    handler: "src/interfaces/controllers/handlers/lgtms.create"
    layers:
      - Ref: "CanvasLambdaLayer"
    events:
      - http:
          method: "post"
          path: "/v1/lgtms"
