service:
  name: "${self:custom.product}"

frameworkVersion: "2"

custom:
  product: "lgtm-generator-api"
  prefix: "${self:custom.product}-${self:provider.stage}"
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
  serverless-offline:
    httpPort: 8080
    useChildProcesses: true
  dynamodb:
    stages: ["dev"]
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - "serverless-webpack"
  - "serverless-offline"
  - "serverless-dynamodb-local"

provider:
  name: "aws"
  profile: "default"
  region: "us-east-1"
  runtime: "nodejs12.x"
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    GOOGLE_API_KEY: "${file(./secrets.yml):googleApiKey}"
    GOOGLE_CUSTOM_SEARCH_ENGINE_ID: "${file(./secrets.yml):googleCustomSearchEngineId}"

layers:
  canvas:
    name: "${self:custom.prefix}-canvas"
    path: "layers/canvas"

functions:
  searchImages:
    timeout: 30
    handler: "src/interfaces/controllers/handlers/images.search"
    layers:
      - Ref: "CanvasLambdaLayer"
    events:
      - http:
          method: "get"
          path: "/v1/images"
          request:
            parameters:
              queryStrings:
                q: true

  createLgtm:
    timeout: 30
    handler: "src/interfaces/controllers/handlers/lgtms.create"
    layers:
      - Ref: "CanvasLambdaLayer"
    events:
      - http:
          method: "post"
          path: "/v1/lgtms"

resources:
  Resources:
    LgtmsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "lgtms"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "created_at"
            AttributeType: "S"
          - AttributeName: "status"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "created_at"
            KeyType: "RANGE"
        GlobalSecondaryIndexes:
          - IndexName: "index_by_status"
            KeySchema:
              - AttributeName: "status"
                KeyType: "HASH"
              - AttributeName: "created_at"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
