version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  node:
    docker:
      - image: lambci/lambda:build-nodejs12.x

commands:
  yarn_install:
    steps:
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --check-files
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  install_yarn:
    steps:
      - run:
          name: install yarn
          command: |
            echo 'export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH' >> $BASH_ENV
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10

jobs:
  test:
    executor: node
    steps:
      - checkout
      - install_yarn
      - yarn_install
      - run: yarn run test
      - slack/status

  lint:
    executor: node
    steps:
      - checkout
      - install_yarn
      - yarn_install
      - run: yarn run lint
      - slack/status

  deploy:
    executor: node
    steps:
      - checkout
      - run: yum -y update
      - run:
          name: install packages for canvas
          command: |
            yum -y install \
              cairo-devel \
              pango-devel \
              libjpeg-turbo-devel
      - install_yarn
      - yarn_install
      - run:
          name: build lambda layers
          command: |
            cp \
              /lib64/libblkid.so.1 \
              /lib64/libjpeg.so.62 \
              /lib64/libpangocairo-1.0.so.0 \
              /lib64/libpng15.so.15 \
              /lib64/libcairo.so.2 \
              /lib64/libmount.so.1 \
              /lib64/libpangoft2-1.0.so.0 \
              /lib64/libuuid.so.1 \
              /lib64/libfreetype.so.6 \
              /lib64/libpango-1.0.so.0 \
              /lib64/libpixman-1.so.0 \
              ./layers/canvas/lib/
      - run: yarn run deploy --stage dev
      - slack/status

workflows:
  build:
    jobs:
      - test
      - lint
      - deploy:
          requires: [test, lint]
